### PR TITLE
Issue #1: Create Xcode project that compiles

### LINKED ISSUE #1: Create Xcode project that compiles
### Requirements
1. Pull request that adds all code
2. Xcode Version 12.3 (12c33) App project 
3. Compiles cleanly on macOS Big Sur, Version 11.1
4. Written in the latest version of Swift
5. Product Name: Menu Bar DNS
6. Organization Identifier: com.ivanstegic.app
7. Menu Bar only app
8. Does not appear in the Command-Tab list of apps
9. Uses SVG icon in Menu Bar `barcode-box-fill` from https://github.com/Remix-Design/RemixIcon/blob/master/icons/Device/barcode-box-fill.svg
10. After startup, icon lives in Menu Bar
11. Click on icon closes the Menu Bar app

Note that these are very basic requirements, this Menu Bar app doesn't do anything at all except that it is able to start up cleanly, implement a specific icon, and stays in the Menu Bar until it is clicked on, at which point the app should exit.

### PR DESCRIPTION
**Pull request by munirahmed007**

### CODE REVIEW

**Comment by ivanstegic** [comment]
Thank you for this @munirahmed007 -- I was able to compile cleanly.

Please could you tell me why the icon was converted to a PNG and was not retained as an SVG?

Also, why are there two PNG files in the Assets.xcassets/menubar-icon.imageset folder?

**Comment by munirahmed007** [comment]
Hi @ivanstegic 

 Previously, Xcode didn't have direct usage of SVG, but Xcode 12 does support it now. The reason, that I still converted it to PNG and with scaling @1x and @2x, is because I thought we might want to deploy it to old MacOS's as well.
 
 The reason two files were added because the image asset in Xcode wants 1x scale for non-retina, and 2x/3x for high resolutions (latest retina screens)

**Comment by ivanstegic** [comment]
Could you please add the SVG instead? I only want to support Big Sur and later.

**Comment by munirahmed007** [comment]
@ivanstegic this has been resolved

**Comment by ivanstegic** [comment]
@munirahmed007  thanks. Could you please retain the original filename? It should be `barcode-box-fill.svg` not `barcode-box-fill (1).svg`

**Comment by munirahmed007** [comment]
done @ivanstegic

**Comment by ivanstegic** [comment]
@munirahmed007 wonderful! This compiles cleanly, works as expected. Can you tell me please, how do I compile it so that it creates an app that I can give to a friend?

**Comment by munirahmed007** [comment]
Hi @ivanstegic 
On right side of Xcode there is project navigator. find Products folder and expand it. You should find DNS menu bar.app under Product folder when you expand it. right click it and select 'Show in finder'. it will open app in finder. from there you can zip and send it to users. Since this app is not signed and notarized they will have to right click and select open option when they want to run it

**Pull request merged**
